DELETE http://localhost:8080/api/contacts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJPc3dhbGRvIGciLCJpYXQiOjE2NTE1MDYzMDB9.D40Ya8HkQny-PQYqWDe0xFm5tNlUNInyVc8zT19zwfc

{
    "id": 123219
}