POST http://localhost:8080/api/login
Content-Type: application/json

{
    "usernameEmail": "iSupp",
    "password": "21941"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "usernameEmail": "Oswaldo g",
    "password": "12344"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "usernameEmail": "oswaldo.gg@gmail.com",
    "password": "oswaldo"
}